### ISSUE TITLE
It was possible to designate dependencies

### ISSUE THREAD

**Issue by woodsleaf** [dalenguyen/wordpress-sage-uikit-starter#1]
It was possible to designate dependencies, such as Python 2+, and so on, to play in the successful installation of this repository, not at all as interesting as you might think. But even so, thank you for the indirect information about the tools that you have implemented, maybe I will find them useful, and I will independently implement them separately from your build.

**Comment by dalenguyen** [comment]
Thanks @woodsleaf, I hope that you like it.
